apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    com.xebialabs.service: invoice-app
  name: invoice-app
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: xebialabsunsupported/ecommerce-invoice:1.0.2
    generation: null
    importPolicy: {}
    name: latest
