apiVersion: v1
kind: Service
metadata:
  labels:
    com.xebialabs.service: invoice-mysql
  name: invoice-mysql
spec:
  ports:
  - name: "mysql"
    port: 3306
    targetPort: 3306
  selector:
    com.xebialabs.service: invoice-mysql
