apiVersion: v1
kind: Service
metadata:
  labels:
    com.xebialabs.service: invoice-app
  name: invoice-app
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    com.xebialabs.service: invoice-app
