apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    com.xebialabs.service: invoice-mysql
  name: invoice-mysql
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: mysql:5.7.20
    generation: null
    importPolicy: {}
    name: 5.7.20