apiVersion: v1
data:
  database-name: aW52b2ljZQo=
  database-password: b0JSQXN4STR4cUh4QWZ1Qw==
  database-root-password: dm1zMEpyczVPNXBlRnYxRQ==
  database-user: aW52b2ljZV91c2VyCg==
kind: Secret
metadata:
  annotations:
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-root_password: '{.data[''database-root-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
  labels:
    app: invoice-mysql
    template: mysql-persistent-template
  name: invoice-mysql
type: Opaque
