apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    app: notification-mongodb
  name: notification-mongodb
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: mongo:3.6.3
    generation: null
    importPolicy: {}
    name: 3.6.3
status:
  dockerImageRepository: ""
