apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    com.xebialabs.service: notification-app
  name: notification-app
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: xebialabsunsupported/ecommerce-notification:1.0.2
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
