apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    com.xebialabs.service: notification-mongodb
  name: notification-mongodb
spec:
  replicas: 1
  selector:
    com.xebialabs.service: notification-mongodb
  strategy:
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    type: Recreate
  template:
    metadata:
      labels:
        com.xebialabs.service: notification-mongodb
    spec:
      containers:
      - image: ' '
        readinessProbe:
          exec:
            command:
              - /bin/sh
              - '-i'
              - '-c'
              - >-
                mongo 127.0.0.1:27017/notification --eval="quit()"
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 27017
          timeoutSeconds: 1
        name: notification-mongodb
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: notification-mongodb-claim0
      restartPolicy: Always
      volumes:
      - name: notification-mongodb-claim0
        persistentVolumeClaim:
          claimName: notification-mongodb-claim0
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - notification-mongodb
      from:
        kind: ImageStreamTag
        name: notification-mongodb:3.6.3
    type: ImageChange