apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    com.xebialabs.service: notification-app
  name: notification-app
spec:
  replicas: 1
  selector:
    com.xebialabs.service: notification-app
  strategy:
    resources: {}
  template:
    metadata:
      labels:
        com.xebialabs.service: notification-app
    spec:
      containers:
      - env:
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: http://admin:admin@jhipster-registry:8761/eureka
        - name: JHIPSTER_REGISTRY_PASSWORD
          value: admin
        - name: JHIPSTER_SLEEP
          value: "10"
        - name: SPRING_CLOUD_CONFIG_URI
          value: http://admin:admin@jhipster-registry:8761/config
        - name: SPRING_DATA_MONGODB_DATABASE
          value: notification
        - name: SPRING_DATA_MONGODB_URI
          value: mongodb://notification-mongodb:27017
        - name: SPRING_PROFILES_ACTIVE
          value: prod,swagger
        image: ' '
        name: notification-app
        resources: {}
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - notification-app
      from:
        kind: ImageStreamTag
        name: notification-app:latest
    type: ImageChange
