apiVersion: v1
kind: Service
metadata:
  labels:
    com.xebialabs.service: notification-mongodb
  name: notification-mongodb
spec:
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    com.xebialabs.service: notification-mongodb