apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    com.xebialabs.service: notification-mongodb
  name: notification-mongodb
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        com.xebialabs.service: notification-mongodb
    spec:
      containers:
      - image: mongo:3.6.3
        name: notification-mongodb
        resources: {}
      restartPolicy: Always
status: {}
