apiVersion: v1
kind: Service
metadata:
  labels:
    com.xebialabs.service: store-mysql
  name: store-mysql
spec:
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306
  selector:
    com.xebialabs.service: store-mysql
