apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: store-mysql-claim0
  name: store-mysql-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi