apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    app: store-app
  name: store-app
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: xebialabsunsupported/ecommerce-store:1.0.2
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
